//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evaluacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evaluacionEntities : DbContext
    {
        public evaluacionEntities()
            : base("name=evaluacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bodega> bodega { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<detalle_compra> detalle_compra { get; set; }
        public virtual DbSet<detalle_venta> detalle_venta { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_costo> producto_costo { get; set; }
        public virtual DbSet<producto_descripcion> producto_descripcion { get; set; }
        public virtual DbSet<producto_precioventa> producto_precioventa { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<venta> venta { get; set; }
    }
}
