//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evaluacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_descripcion
    {
        public int idproducto_descripcion { get; set; }
        public Nullable<int> idproducto { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
